<div class="container body-content">
		<div class="media">
			<div class="media-left hidden-xs">
					<img class="media-object" src="imgs/img.png" height="170" width="170" alt="Hartur Barreto Brito">
					<font color="white">
						<h4>Hartur Barreto Brito</h4>
						<h5>23 anos</h5>
						<h5>Recife - PE</h5>
					</font>
			</div>

			<div class="hidden-sm hidden-md hidden-lg">
					<img src="imgs/img.png" height="85" width="85" alt="Hartur Barreto Brito">
					<font color="white">
						<h4>Hartur Brito</h4>
						<h5>23 anos</h5>
						<h5>Recife - PE</h5>
					</font>
			</div>